name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  http: ^1.2.2

  go_router: ^10.0.0
  intl: ^0.19.0
  chopper: ^8.0.3
  balanced_text: ^0.0.3
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.9
  chopper_generator: ^8.0.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
