# Generated by Django 5.1.3 on 2024-12-06 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city', models.CharField(max_length=200)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255, null=True)),
                ('dob', models.DateField(null=True)),
                ('login', models.CharField(max_length=180, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('surname', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('status', models.CharField(choices=[('SENT', 'Отправленно'), ('RECEIVED', 'Получено'), ('READ', 'Прочитано'), ('REJECTED', 'Отклонено')], default='SENT', max_length=30)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.user')),
            ],
        ),
    ]
