# Generated by Django 5.1.3 on 2024-12-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='en_city',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SEND', 'Отправленно'), ('READ', 'Прочитано'), ('RECEIVED', 'Получено'), ('REJECTED', 'Отклонено')], default='SEND', max_length=30),
        ),
    ]
