# Generated by Django 5.1.3 on 2024-12-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_city_en_city_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
