# Generated by Django 5.1.3 on 2024-12-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_city_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='en_city',
            new_name='city_en',
        ),
    ]
