# Generated by Django 5.1.3 on 2025-01-10 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_en_city_city_city_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('weather_type', models.CharField(max_length=255, null=True)),
                ('pressure', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_city', to='app.city')),
            ],
        ),
    ]
