# Generated by Django 5.1.3 on 2025-01-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_forecast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='weather_type',
            new_name='conditions',
        ),
        migrations.AddField(
            model_name='forecast',
            name='max_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='min_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='wind_speed',
            field=models.FloatField(null=True),
        ),
    ]
