# Generated by Django 5.1.3 on 2025-01-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_weather_type_forecast_conditions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='text',
        ),
        migrations.AddField(
            model_name='application',
            name='total_attachments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('WA', 'Ожидает рассмотрения'), ('WO', 'В работе'), ('IR', 'Требуется информация'), ('CO', 'Завершено')], default='WA', max_length=2),
        ),
        migrations.CreateModel(
            name='FileApplicationAttachments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_in_order', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to='app.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='InfoApplicationAttachments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_in_order', models.IntegerField()),
                ('info', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_attachments', to='app.application')),
            ],
        ),
        migrations.CreateModel(
            name='TextApplicationAttachments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_in_order', models.IntegerField()),
                ('text', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_attachments', to='app.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_attachments', to='app.user')),
            ],
        ),
    ]
