# Generated by Django 5.1.3 on 2025-01-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_application_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='max_temp',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='min_temp',
        ),
    ]
