# Generated by Django 5.1.3 on 2025-01-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_forecast_max_temp_remove_forecast_min_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('AD', 'Администратор'), ('US', 'Пользователь')], default='US', max_length=2),
        ),
    ]
