# Generated by Django 5.1.3 on 2025-01-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileapplicationattachments',
            name='file',
            field=models.FileField(upload_to='attachments/%Y/%m/%d'),
        ),
    ]
